name: ninjaone-ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
concurrency:
  group: "ninjaone-ci-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  nightwatch-tests:
    name: Run Nightwatch tests
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Set up repository
        uses: actions/checkout@v3
        
      - name: Install dependencies
        shell: bash
        run: npm install

      - name: Install Chrome
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run Nightwatch tests
        shell: bash
        run: npx nightwatch --tag login